src/config/routes.rb
Rails.application.routes.draw do
  root :to => 'static#index'

  ActiveAdmin.routes(self)

  resources :events do
    member do
      get :export
    end
  end

  scope controller: :housing_rooms do
    get 'housing' => :show_buildings, :as => :housing_rooms
    get 'housing/dorms/:dorm_id' => :show_building_rooms, :as => :show_housing_rooms_for_dorm
    get 'housing/rooms/:room_id' => :show, :as => :show_housing_room
  end

  scope controller: :housing_reviews do
    get 'housing/rooms/:room_id/reviews/' => :index, :as => :housing_reviews
    post 'housing/rooms/:room_id/reviews/' => :create, :as => :create_housing_review
    get 'housing/rooms/:room_id/reviews/new' => :new, :as => :new_housing_review
    get 'housing/rooms/:room_id/reviews/:id' => :show, :as => :housing_review
    delete 'housing/rooms/:room_id/reviews/:id' => :destroy, :as => :delete_housing_review
  end

  scope controller: :course_reviews do
    get 'reviews/courses' => :show_course_reviews, as: :course_reviews
    get 'reviews/instructors' => :show_instructor_reviews, as: :instructor_reviews
    get 'reviews/courses/:course_id/new' => :new, as: :new_course_review
    post 'reviews/courses/search' => :search_course_reviews, as: :course_reviews_search
    post 'reviews/instructors/search' => :search_instructor_reviews, as: :instructor_reviews_search
    post 'reviews/courses' => :create, as: :create_course_review
    delete 'reviews/:id' => :destroy, :as => :delete_course_review
  end

  scope controller: :courses do
    get 'courses/planner' => :index, as: :course_planner
    get 'courses/planner/export' => :export_course_sections, as: :courses_export
    post 'courses/planner/add' => :add_course_section_to_schedule, as: :courses_add
    post 'courses/planner/remove' => :remove_course_section_from_schedule, as: :courses_remove
    post 'courses/planner/clear' => :clear_course_sections_from_schedule, as: :courses_clear
    post 'courses/planner/save' => :save_course_sections_to_schedule, as: :courses_save

    match 'courses/search' => :search_course_sections, :via => [:get, :post]

    get 'courses/:id/review' => :add_review_course_section, as: :review_course_section
    get 'courses/:id' => :show, as: :course
  end

  scope controller: :instructors do
    get 'instructors' => :index
    get 'instructors/:id/review' => :add_instructor_review, as: :review_instructor
    get 'instructors/:id' => :show, as: :instructor
    match 'instructors/search' => :search, :via => [:get, :post]
  end

  scope controller: :menu do
    get 'menus' => :index
    match 'menus/:dining_hall' => :show, :via => [:get, :post]
    match 'menus/:meal_type' => :show, :via => [:get, :post]
  end

  scope controller: :sessions do
    get 'unauthorized' => :not_authorized
    match 'logout' => :destroy, :via => [:get, :destroy]
    get 'login' => :new
    match 'login/cas' => :create_via_cas, :via => [:get, :post]
    match 'login/credentials' => :create_via_credentials, :via => [:get, :post]
    match 'login/create_account' => :create_new_account, :via => [:get, :post]
  end

  scope controller: :static do
    # Hardcoded pages not created via the CMS
    get 'index' => :index
    get 'senators' => :senators
    get 'housing-platform' => :housing_platform
    get 'career-opportunities' => :career_opportunities
    
    match 'contact-aspc' => :open_forum, :via => [:get, :post]

    # Editable pages created via the CMS
    get 'pages/id/:id' => :show, as: :static_page
    get 'pages/:page_name' => :show, as: :static

    post 'pages/:id/update' => 'static#save', as: :static_page_update
    post 'pages/:id/upload_image' => 'static#upload_image', as: :static_page_upload_image
    post 'pages/:id/delete_image' => 'static#delete_image', as: :static_page_delete_image
    post 'pages/:id/upload_file' => 'static#upload_file', as: :static_page_upload_file
    post 'pages/:id/delete_file' => 'static#delete_file', as: :static_page_delete_file

    get '/uploads/:image_name' => :load_image
  end
end

src/app/models/static.rb
class Static < ApplicationRecord
  belongs_to :last_modified_by, class_name: "User", foreign_key: "last_modified_by", :optional => true

  validates_uniqueness_of :page_name, :allow_nil => true, :allow_blank => true # allows nil fields
  validate :can_publish?

  def approve!
    self.approved_content = self.pending_content

    self.published = true
    self.save
  end

  private

  def can_publish?
    if self.published == true
      if self.page_name.blank?
        errors.add(:page_name, "cannot be empty")
      end

      if Static.where.not(:id => self.id).exists?(:page_name => self.page_name)
        errors.add(:page_name, "must be unique")
      end
    end

    return errors.nil? # Return true if can publish
  end

end

src/app/controllers/static_controller.rb
class StaticController < ApplicationController
  # Custom form in activeadmin breaks CSRF
  # This is a workaround while we figure out a better solution
  # skip_before_action :verify_authenticity_token, :only => [:upload_image]
  skip_before_action :verify_authenticity_token, :except => [:open_forum]
  before_action :authenticate_user!, :only => [:open_forum]

  # Reference: https://github.com/froala/editor-ruby-sdk-example
  # https://www.froala.com/wysiwyg-editor/docs/sdks/ruby/image-server-upload

  def show
    if params[:id]
      @page = Static.find_by(:id => params[:id])
    elsif params[:page_name]
      @page = Static.find_by(:page_name => params[:page_name])
    end

    if @page.nil?
      raise ActionController::RoutingError, 'Not Found'
    end
  end

  # Save content to database
  def save
    @page = Static.find_by_id(params[:id])
    @page[:pending_content] = params[:content]
    @page[:last_modified_by] = current_user[:id]
    @page[:published] = false

    @page.save
  end

  # Approve changes: copy pending_copy to approved_copy
  # def approve
  #   @page = Static.find_by_id(params[:id])
  #   @page[:approved_content] = @page[:pending_content]

  #   @page.save
  # end

  # Upload file.
  def upload_file
    render :json => FroalaEditorSDK::File.upload(params, "public/uploads/")
  end

  # Delete file.
  def delete_file
    render :json => FroalaEditorSDK::File.delete(params[:src], "public/uploads/")
  end

  # Upload image.
  def upload_image
    render :json => FroalaEditorSDK::Image.upload(params, "public/uploads/")
  end

  # Load images.
  def load_images
    render :json => FroalaEditorSDK::Image.load_images("public/uploads/")
  end

  # Load an image.s
  def load_image
    if File.exists?(Rails.root.join("public", "uploads", params[:image_name]))
      send_data File.read(Rails.root.join("public", "uploads", "images", params[:name])), :filename => ::File.basename(params[:name]), :disposition => 'inline'
    else
      head :not_found
    end
  end

  # Delete image.
  def delete_image
    render :json => FroalaEditorSDK::Image.delete(params[:src], "public/uploads/")
  end

  ##
  # Custom actions for special, hardcoded views
  def index
    @announcements = Announcement.priority_order.all
    time = Time.parse(Time.now.in_time_zone("Pacific Time (US & Canada)").strftime('%Y-%m-%d %H:%M:%S')).to_s(:db)
    @events = Event.where("start >= ?", time).where(:status => :approved).order(:start).take(9)
    @news = news
  end

  def senators
    @senators = Person.priority_order.order("id ASC")
  end

  def staff
    @staff = Person.priority_order.staff.order("id ASC")
    @board = Person.priority_order.board.order("id ASC")
  end

  def housing_platform
  end

  def open_forum
    respond_to do |format|
      # Validate parameters
      valid_params = %w[topic question response response_method]
      valid_params.each do |param|
        unless params.has_key? param
          format.js {
            render partial: "components/toast",
                   locals: {
                       message: "Invalid request.",
                       type: "is-danger"
                   }
          }
        end
      end

      # Find an email associated with the provided topic
      begin
        topic_email_mapping = OpenForumMapping.find(params[:topic])
      rescue
        format.js {
          render partial: "components/toast",
                 locals: {
                     message: "Could not find an email for the selected area of concern.",
                     type: "is-danger"
                 }
        }
        return
      end

      # Assign parameters
      question = params[:question]
      should_respond = params[:response]
      response_method = params[:response_method]
      to = topic_email_mapping.email

      # Make sure that the question is not empty and that the response method is not empty in case the user wanted a response
      if not question.blank? and (should_respond == "true" and not response_method.blank? or should_respond == "false")
        OpenForumMailer.with(question: question, should_respond: should_respond, response_method: response_method, to: to).new_open_forum_email.deliver_later
        format.js {
          render partial: "components/toast",
                 locals: {
                     message: "Your message has been sent!",
                     type: "is-success"
                 }
        }
      else
        format.js {
          render partial: "components/toast",
                 locals: {
                     message: "An error occurred while sending your message. Please check your form and try again.",
                     type: "is-danger"
                 }
        }
      end
      format.html
    end
  end

  private

  def news
    require 'rss'
    require 'open-uri'

    rss_results = []
    rss = RSS::Parser.parse(open("https://tsl.news/feed").read, false).items[0..2]

    rss.each do |result|
      html = Nokogiri::HTML(result.description)
      description = html.xpath("//p")[0].to_s + "..."
      result = {title: result.title, date: result.pubDate, link: result.link, description: description}
      rss_results.push(result)
    end
    return rss_results
  end
end

src/app/helpers/static_helper.rb
module StaticHelper

  # Method used to set a class based on event's college affiliation in events slideshow on homepage
  def bg_color_class(item)
    case item.college_affiliation.try(:to_sym)
    when :pomona
      "event-PO"
    when :claremont_mckenna
      "event-CM"
    when :harvey_mudd
      "event-HM"
    when :scripps
      "event-SC"
    when :pitzer
      "event-PZ"
    else
      "event-PO" # catchall because Frank/Frary/Oldenborg to not symbolize to Pomona
    end
  end

  # Profile picture image helper for senator/staff profiles
  def avatar_photo (person)
    if person.image.attached?
      image_tag person.image
    else
      image_tag "static/placeholder.jpg"
    end
  end

end

src/app/views/admin/statics/_static_page_content_editor.html.erb
<% page = local_assigns.fetch(:page) %>

<div id="static-page-editor">
  <div id="saveComplete">
    <strong>Page Saved!</strong>
  </div>
  <br/>

  <textarea id="editor"></textarea>

  <br />
  <%= link_to "Save Content", {}, :remote => true, :id => "saveButton", :class => "button" %>
  <%= link_to "Preview Page", static_page_path, :method => :get, :class=>"button" %>
  <span id="saveSpinner" class="fa-2x">
      <i class="fa fa-spinner fa-spin"></i>
  </span>
</div>

<script type="text/javascript">
    $(function() {
        $("#saveSpinner").hide();
        $("#saveComplete").hide();

        $("#editor").froalaEditor({
            // License Key
            key: "<%= Rails.application.credentials[:froala_license_keys][:production] %>",

            // Set the save param.
            saveParam: "content",

            // Set the save URL.
            saveURL: "<%= static_page_update_path %>",

            // HTTP request type.
            saveMethod: "POST",

            // Disable autosave
            saveInterval: 0,

            // Additional save params.
            saveParams: {id: "my_editor"},

            // Route for uploading images
            imageUploadURL: "<%= static_page_upload_image_path %>",

            fileUploadURL: "<%= static_page_upload_file_path %>",

            // Hide character counter
            charCounterCount: false
        });

        $("#editor").on("froalaEditor.contentChanged", function(e, editor) {
            $("#saveComplete").hide();
        });

        $("#editor").on("froalaEditor.save.before", function(e, editor) {
            $("#saveSpinner").show();
            $("#saveComplete").hide();
        });

        $("#editor").on("froalaEditor.save.after", function(e, editor, response) {
            $("#saveSpinner").hide();
            $("#saveComplete").show();
            console.log("save.after");
        });

        $("#editor").on("froalaEditor.image.error", function(e, editor, error) {
            var popup = editor.popups.get('image.insert');
            var layer = popup.find('.fr-image-progress-bar-layer');
            layer.find('h3').text('Image size must be less than 1 MB. Please resize the photo and try again.');
        });

        $("#editor").on('froalaEditor.image.removed', function (e, editor, img) {
            $.ajax({
                // Request method.
                method: "POST",

                // Request URL.
                url: "<%= static_page_delete_image_path %>",

                // Request params.
                data: {
                    src: img.attr('src')
                }
            });
        });

        $("#editor").on('froalaEditor.file.unlink', function (e, editor, link) {
            $.ajax({
                // Request method.
                method: "POST",

                // Request URL.
                url: "<%= static_page_delete_file_path %>",

                // Request params.
                data: {
                    src: link.href
                }
            });
        });

        // Load the existing preview
        let content = "<%= page.pending_content %>"
        decodedContent = $("<textarea></textarea>").html(content).text();   // ampersand-decoding

        $("#editor").froalaEditor("html.set", decodedContent);
    });

    $("#saveButton").click(function() {
        $("#editor").froalaEditor("save.save");
    });
</script>

src/app/views/admin/statics/_static_page_edit_form.html.erb
<!-- Remote form to update title and subtitle -->
<% page = Static.find_by_id(params[:id]) %>
<% role = current_user.role.to_sym %>

<%= semantic_form_for [role, resource], :remote => (page.present?), builder: ActiveAdmin::FormBuilder do |f| %>
  <%=  f.inputs do %>
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <% if current_user.role.to_sym == :admin %> <!-- Allow admins (not moderators) to change the page url name -->
      <%= f.input :page_name %>
    <% end %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :label => "Update Heading" %>
  <% end %>
<% end %>

<!-- Form to update website content if page exists -->
<% if page.present? %>
  <%= render 'static_page_content_editor', page: page %>
<% end %>