config/routes.rb
Rails.application.routes.draw do
  root :to => 'static#index'

  ActiveAdmin.routes(self)

  resources :events do
    member do
      get :export
    end
  end

  scope controller: :housing_rooms do
    get 'housing' => :show_buildings, :as => :housing_rooms
    get 'housing/dorms/:dorm_id' => :show_building_rooms, :as => :show_housing_rooms_for_dorm
    get 'housing/dorms/:dorm_id/floor_plans' => :floor_plans, :as => :floor_plans
    get 'housing/rooms/:room_id' => :show, :as => :show_housing_room
  end

  scope controller: :housing_reviews do
    get 'housing/rooms/:room_id/reviews/' => :index, :as => :housing_reviews
    post 'housing/rooms/:room_id/reviews/' => :create, :as => :create_housing_review
    get 'housing/rooms/:room_id/reviews/new' => :new, :as => :new_housing_review
    get 'housing/rooms/:room_id/reviews/:id' => :show, :as => :housing_review
    delete 'housing/rooms/:room_id/reviews/:id' => :destroy, :as => :delete_housing_review
  end

  scope controller: :course_reviews do
    get 'reviews/courses' => :show_course_reviews, as: :course_reviews
    get 'reviews/instructors' => :show_instructor_reviews, as: :instructor_reviews
    get 'reviews/courses/:course_id/new' => :new, as: :new_course_review
    post 'reviews/courses/search' => :search_course_reviews, as: :course_reviews_search
    post 'reviews/instructors/search' => :search_instructor_reviews, as: :instructor_reviews_search
    post 'reviews/courses' => :create, as: :create_course_review
    delete 'reviews/:id' => :destroy, :as => :delete_course_review
  end

  scope controller: :courses do
    get 'courses/planner' => :index, as: :course_planner
    get 'courses/planner/export' => :export_course_sections, as: :courses_export
    post 'courses/planner/add' => :add_course_section_to_schedule, as: :courses_add
    post 'courses/planner/remove' => :remove_course_section_from_schedule, as: :courses_remove
    post 'courses/planner/clear' => :clear_course_sections_from_schedule, as: :courses_clear
    post 'courses/planner/save' => :save_course_sections_to_schedule, as: :courses_save

    match 'courses/search' => :search_course_sections, :via => [:get, :post]

    get 'courses/:id/review' => :add_review_course_section, as: :review_course_section
    get 'courses/:id' => :show, as: :course
  end

  scope controller: :instructors do
    get 'instructors' => :index
    get 'instructors/:id/review' => :add_instructor_review, as: :review_instructor
    get 'instructors/:id' => :show, as: :instructor
    match 'instructors/search' => :search, :via => [:get, :post]
  end

  scope controller: :menu do
    get 'menus' => :index
    match 'menus/:dining_hall' => :show, :via => [:get, :post]
    match 'menus/:meal_type' => :show, :via => [:get, :post]
  end

  scope controller: :sessions do
    get 'unauthorized' => :not_authorized
    match 'logout' => :destroy, :via => [:get, :destroy]
    get 'login' => :new
    match 'login/cas' => :create_via_cas, :via => [:get, :post]
    match 'login/credentials' => :create_via_credentials, :via => [:get, :post]
    match 'login/create_account' => :create_new_account, :via => [:get, :post]
  end

  scope controller: :static do
    # Hardcoded pages not created via the CMS
    get 'index' => :index
    get 'senators' => :senators
    get 'staff' => :staff
    get 'sdg' => :sdg
    get 'housing-platform' => :housing_platform
    get 'career-opportunities' => :career_opportunities
    get 'seniorclass' => :senior_class
    
    match 'contact-aspc' => :open_forum, :via => [:get, :post]

    # Editable pages created via the CMS
    get 'pages/id/:id' => :show, as: :static_page
    get 'pages/:page_name' => :show, as: :static

    post 'pages/:id/update' => 'static#save', as: :static_page_update
    post 'pages/:id/upload_image' => 'static#upload_image', as: :static_page_upload_image
    post 'pages/:id/delete_image' => 'static#delete_image', as: :static_page_delete_image
    post 'pages/:id/upload_file' => 'static#upload_file', as: :static_page_upload_file
    post 'pages/:id/delete_file' => 'static#delete_file', as: :static_page_delete_file

    get '/uploads/:image_name' => :load_image
  end
end

app/views/instructors/show.html.erb
<% content_for :header do %>
  <%= render 'components/page_header', :title => @instructor.name, :subtitle => "Reviews for #{@instructor.name}" %>
<% end %>

<% if @instructor.course_reviews.length > 0 and not @instructor.name == "Staff" %>
  <h2 class="title">Overall instructor rating: &nbsp;
    <span class="has-text-warning">
      <%= render 'components/numerical_review', rating: @instructor.overall_rating, tag_classes: 'is-large is-info', show_icon: true %>
    </span>
  </h2>
  <div class="columns">
    <div class="column">
      <h3 class="subtitle">
        Challenge rating: <%= render 'components/numerical_review', rating: @instructor.challenge_rating, tag_classes: 'is-medium' %>
      </h3>
    </div>
    <div class="column">
      <h3 class="subtitle">
        Inclusivity rating: <%= render 'components/numerical_review', rating: @instructor.inclusivity_rating, tag_classes: 'is-medium' %>
      </h3>
    </div>
    <div class="column">
      <h3 class="subtitle">
        Average work per week: <span class="tag is-medium"><%= @instructor.work_per_week %> hours</span>
      </h3>
    </div>
  </div>
  <hr />
  <% @instructor.course_reviews.each do |review| %>
    <div class="columns">
      <div class="column">
        <div class="tags are-normal">
        <span class="tag is-medium">
          Instructor rating: &nbsp;
          <span class="has-text-warning">
            <%= render 'components/star_review', rating: review.overall_rating %>
          </span>
        </span>
        </div>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <p class="subtitle"><%= review.comments %></p>
        <p><%= link_to course_path(review.course), :class => 'no-underline has-text-dark' do %>
            <%= review.course.name %>
            <%= render 'components/numerical_review',
                       rating: review.course.overall_rating %>
          <% end %></p>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <p><span class="tag has-background-white-bis"><%= review.work_per_week %> Hours work per week</span></p>
        <p>
        <span class="tag has-background-white-bis">
          <span class="has-text-grey">
            <%= render 'components/star_review', rating: review.challenge_rating %>
          </span> &nbsp; Challenge rating
        </span>
        </p>
        <p>
          <% if review.inclusivity_rating %>
          <span class="tag has-background-white-bis">
            <span class="has-text-grey">
              <%= render 'components/star_review', rating: review.inclusivity_rating %>
            </span> &nbsp; Inclusivity rating
          </span>
          <% end %>
        </p>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <p><em>Review written <%= review.written_at %></em></p>
      </div>
    </div>
    <% if !current_user.nil? && review.user_id == current_user.id %>
      <div class="columns">
        <div class="column">
          <%= link_to "Delete", delete_course_review_path(review), :method => 'delete', class: "button is-danger is-outlined" %>
        </div>
      </div>
    <% end %>
    <hr />
  <% end %>
<% else %>
  <div class="columns">
    <div class="column">
      <p class="subtitle">There are no reviews for this instructor at this time.</p>
    </div>
  </div>
<% end %>