config/routes.rb
Rails.application.routes.draw do
  root :to => 'static#index'

  ActiveAdmin.routes(self)

  resources :events do
    member do
      get :export
    end
  end

  scope controller: :housing_rooms do
    get 'housing' => :show_buildings, :as => :housing_rooms
    get 'housing/dorms/:dorm_id' => :show_building_rooms, :as => :show_housing_rooms_for_dorm
    get 'housing/dorms/:dorm_id/floor_plans' => :floor_plans, :as => :floor_plans
    get 'housing/rooms/:room_id' => :show, :as => :show_housing_room
  end

  scope controller: :housing_reviews do
    get 'housing/rooms/:room_id/reviews/' => :index, :as => :housing_reviews
    post 'housing/rooms/:room_id/reviews/' => :create, :as => :create_housing_review
    get 'housing/rooms/:room_id/reviews/new' => :new, :as => :new_housing_review
    get 'housing/rooms/:room_id/reviews/:id' => :show, :as => :housing_review
    delete 'housing/rooms/:room_id/reviews/:id' => :destroy, :as => :delete_housing_review
  end

  scope controller: :course_reviews do
    get 'reviews/courses' => :show_course_reviews, as: :course_reviews
    get 'reviews/instructors' => :show_instructor_reviews, as: :instructor_reviews
    get 'reviews/courses/:course_id/new' => :new, as: :new_course_review
    post 'reviews/courses/search' => :search_course_reviews, as: :course_reviews_search
    post 'reviews/instructors/search' => :search_instructor_reviews, as: :instructor_reviews_search
    post 'reviews/courses' => :create, as: :create_course_review
    delete 'reviews/:id' => :destroy, :as => :delete_course_review
  end

  scope controller: :courses do
    get 'courses/planner' => :index, as: :course_planner
    get 'courses/planner/export' => :export_course_sections, as: :courses_export
    post 'courses/planner/add' => :add_course_section_to_schedule, as: :courses_add
    post 'courses/planner/remove' => :remove_course_section_from_schedule, as: :courses_remove
    post 'courses/planner/clear' => :clear_course_sections_from_schedule, as: :courses_clear
    post 'courses/planner/save' => :save_course_sections_to_schedule, as: :courses_save

    match 'courses/search' => :search_course_sections, :via => [:get, :post]

    get 'courses/:id/review' => :add_review_course_section, as: :review_course_section
    get 'courses/:id' => :show, as: :course
  end

  scope controller: :instructors do
    get 'instructors' => :index
    get 'instructors/:id/review' => :add_instructor_review, as: :review_instructor
    get 'instructors/:id' => :show, as: :instructor
    match 'instructors/search' => :search, :via => [:get, :post]
  end

  scope controller: :menu do
    get 'menus' => :index
    match 'menus/:dining_hall' => :show, :via => [:get, :post]
    match 'menus/:meal_type' => :show, :via => [:get, :post]
  end

  scope controller: :sessions do
    get 'unauthorized' => :not_authorized
    match 'logout' => :destroy, :via => [:get, :destroy]
    get 'login' => :new
    match 'login/cas' => :create_via_cas, :via => [:get, :post]
    match 'login/credentials' => :create_via_credentials, :via => [:get, :post]
    match 'login/create_account' => :create_new_account, :via => [:get, :post]
  end

  scope controller: :static do
    # Hardcoded pages not created via the CMS
    get 'index' => :index
    get 'senators' => :senators
    get 'staff' => :staff
    get 'sdg' => :sdg
    get 'housing-platform' => :housing_platform
    get 'career-opportunities' => :career_opportunities
    get 'seniorclass' => :senior_class
    
    match 'contact-aspc' => :open_forum, :via => [:get, :post]

    # Editable pages created via the CMS
    get 'pages/id/:id' => :show, as: :static_page
    get 'pages/:page_name' => :show, as: :static

    post 'pages/:id/update' => 'static#save', as: :static_page_update
    post 'pages/:id/upload_image' => 'static#upload_image', as: :static_page_upload_image
    post 'pages/:id/delete_image' => 'static#delete_image', as: :static_page_delete_image
    post 'pages/:id/upload_file' => 'static#upload_file', as: :static_page_upload_file
    post 'pages/:id/delete_file' => 'static#delete_file', as: :static_page_delete_file

    get '/uploads/:image_name' => :load_image
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!

  def index
    @academic_terms = AcademicTerm.current_academic_year
    @departments = Department.all
    @course_meeting_details = CourseMeetingDetail.all

    user_course_schedule = CourseSchedule.find_or_create_by(:user => current_user)
    @course_sections = user_course_schedule.course_sections
  end

  def show
    @course = Course.find(params[:id])
  end

  def export_course_sections
    user_course_schedule = CourseSchedule.find_by(:user => current_user)
    course_sections = user_course_schedule.course_sections.includes(:course_meeting_details).where.not(course_meeting_details: {course_section_id: nil})
    academic_term = course_sections.first&.academic_term

    if !academic_term # Academic Term is decided by the courses on the schedule
      return redirect_to course_planner_path, :flash => {
          :notice => "Cannot export schedule.",
          :notice_subtitle => "You haven't saved any courses to your schedule!",
          :notice_class => "is-danger",
      }
    end

    calendar = Icalendar::Calendar.new
    calendar.version = "2.0"
    filename = "#{academic_term.session.parameterize}-#{academic_term.year}-courses.ics"

    case academic_term.key
    when "2019;SP"
      term_start = DateTime.new(2019, 1, 22, 8, 10, 0)
      term_end = DateTime.new(2019, 5, 8, 22, 0, 0)
    when "2019;FA"
      term_start = DateTime.new(2019, 9, 3, 8, 10, 0)
      term_end = DateTime.new(2019, 12, 11, 22, 0, 0)
    when "2020;SP"
      term_start = DateTime.new(2020, 1, 21, 8, 10, 0)
      term_end = DateTime.new(2020, 5, 6, 22, 0, 0)
    when "2020;FA"
      term_start = DateTime.new(2020, 9, 1, 8, 10, 0)
      term_end = DateTime.new(2020, 12, 9, 22, 0, 0)
    when "2021;SP"
      term_start = DateTime.new(2021, 1, 25, 8, 10, 0)
      term_end = DateTime.new(2021, 5, 6, 22, 0, 0)
    when "2022;FA"
      term_start = DateTime.new(2022, 8, 29, 8, 10, 0)
      term_end = DateTime.new(2022, 12, 7, 22, 0, 0)
    when "2023;SP"
      term_start = DateTime.new(2023, 1, 17, 8, 10, 0)
      term_end = DateTime.new(2023, 5, 3, 22, 0, 0)
    when "2023;FA"
      term_start = DateTime.new(2023, 8, 28, 8, 10, 0)
      term_end = DateTime.new(2023, 12, 15, 22, 0, 0)
    when "2024;SP"
      term_start = DateTime.new(2024, 1, 16, 8, 10, 0)
      term_end = DateTime.new(2024, 5, 10, 22, 0, 0)
    when "2024;FA"
      term_start = DateTime.new(2024, 8, 26, 8, 10, 0)
      term_end = DateTime.new(2024, 12, 13, 22, 0, 0)
    when "2025;SP"
      term_start = DateTime.new(2025, 1, 21, 8, 10, 0)
      term_end = DateTime.new(2025, 5, 16, 22, 0, 0)
    else
      return redirect_to course_planner_path # This is temporary and MUST be made into something more permanent than hardcoding
    end

    (term_start..term_end).each do |date|
       course_sections.each do |course_section|
        course_section.course_meeting_details.each do |detail|
          case date.strftime("%w")
          when "1"
            if detail.monday
              new_calendar_event(calendar, date, course_section, detail)
            end
          when "2"
            if detail.tuesday
              new_calendar_event(calendar, date, course_section, detail)
            end
          when "3"
            if detail.wednesday
              new_calendar_event(calendar, date, course_section, detail)
            end
          when "4"
            if detail.thursday
              new_calendar_event(calendar, date, course_section, detail)
            end
          when "5"
            if detail.friday
              new_calendar_event(calendar, date, course_section, detail)
            end
          end
        end
      end
    end

    send_data calendar.to_ical, type: "text/calendar", disposition: "attachment", filename: filename
  end

# TODO: Move to course schedule controller ?
  def add_course_section_to_schedule
    section_id = params[:section_id]
    @course_section = CourseSection.find_by(:id => section_id)

    @course_schedule = CourseSchedule.find_or_create_by(:user => current_user)
    if (@course_schedule.course_sections.none? {|section| section.code_slug == @course_section.code_slug})
      @course_schedule.course_sections << @course_section
      @course_schedule.save
    end

    respond_to do |format|
      format.js
    end
  end

# TODO: Move to course schedule controller ?
  def remove_course_section_from_schedule
    @course_schedule = CourseSchedule.find_or_create_by(:user => current_user)

    section_id = params[:section_id]
    @course_section = CourseSection.find_by(:id => section_id)
    @course_schedule.course_sections.delete(@course_section)

    respond_to do |format|
      format.js
    end
  end

# TODO: Move to course schedule controller ?
  def clear_course_sections_from_schedule
    @course_schedule = CourseSchedule.find_or_create_by(:user => current_user)
    @course_schedule.course_sections.delete(*@course_schedule.course_sections)

    respond_to do |format|
      format.js
    end
  end

# TODO: Move to course schedule controller ?
# This method is actually completely redundant,
# but mas as well provide a placebo / verification
  def save_course_sections_to_schedule
    respond_to do |format|
      format.js {flash.now[:notice] = "Schedule saved successfully."}
    end
  end

# TODO: Refactor this - break it up into manageable components
# Possibly separate search into a separate module entirely (as it is used similarly in course reviews)
  def search_course_sections
    if params[:academic_term].nil? || params[:academic_term].empty?
      return render :json => {error: "No academic term specified"}, :status => :bad_request
    end

    avoid_schedule = params[:avoid_schedule]
    course_schedule = CourseSchedule.find_or_create_by(:user => current_user)
    term_key = params[:academic_term].split.reverse.join(';')
    department_code = Department.find_by(:name => params[:department]).code unless params[:department].empty?
    instructor_name = params[:instructor].strip unless params[:instructor].empty?
    number = params[:number].to_i rescue nil unless params[:number].empty?
    keywords = params[:keywords].split rescue nil unless params[:keywords].empty?

    start_hour = params["start_time(4i)"].to_i rescue nil unless params["start_time(4i)"].empty?
    start_minute = params["start_time(5i)"].to_i rescue nil unless params["start_time(5i)"].empty?
    end_hour = params["end_time(4i)"].to_i rescue nil unless params["end_time(4i)"].empty?
    end_minute = params["end_time(5i)"].to_i rescue nil unless params["end_time(5i)"].empty?

    consider_time = false
    if not start_hour.nil?  # if user specifies start time
      start_time = ActiveSupport::TimeZone['UTC'].local(1970, 1, 1, start_hour, start_minute).to_datetime
    
      if end_hour.nil? then end_hour = 23 end   # if user doesn't specify end time, set default value to display all classes after start time
      end_time = ActiveSupport::TimeZone['UTC'].local(1970, 1, 1, end_hour, end_minute).to_datetime
      consider_time = true

    elsif not end_hour.nil?   # if user only specifies end time but not start time
      end_time = ActiveSupport::TimeZone['UTC'].local(1970, 1, 1, end_hour, end_minute).to_datetime
      
      if start_hour.nil? then start_hour = 0 end   # double check that user did not set start time, set default value to display all classes before end time
      start_time = ActiveSupport::TimeZone['UTC'].local(1970, 1, 1, start_hour, start_minute).to_datetime
      consider_time = true
    end
    Rails.logger.info "TIME INFORMATION"
    Rails.logger.info "#{start_hour} #{end_hour}"
    Rails.logger.info "#{start_time} #{end_time}"

    # Gets results from individual checkboxes with corresponding symbols
    schools = {
        :pomona => params[:pomona] || false,
        :claremont_mckenna => params[:claremont_mckenna] || false,
        :harvey_mudd => params[:harvey_mudd] || false,
        :scripps => params[:scripps] || false,
        :pitzer => params[:pitzer] || false
    }
    schools.select! {|k,v| v}
    if schools.length > 0
      schools = schools.keys
    else
      schools = CourseMeetingDetail.campus.keys
    end

    # Gets results from individual checkboxes with corresponding symbols
    days = {
        :monday => params[:monday] || false,
        :tuesday => params[:tuesday] || false,
        :wednesday => params[:wednesday] || false,
        :thursday => params[:thursday] || false,
        :friday => params[:friday] || false
    }
    days.select! {|k, v| v}

    matches_query = CourseSection
                        .joins(:academic_term)
                        .joins(:course => [:departments])
                        .where(:academic_terms => {:key => term_key})

    if (days.length > 0)
      matches_query = matches_query
                          .joins(:course_meeting_details)
                          .where(:course_meeting_details => days)
    end

    if (consider_time)
      matches_query = matches_query
                           .joins(:course_meeting_details)
                           .where(:course_meeting_details => {:start_time => start_time..end_time})
                           .where(:course_meeting_details => {:end_time => start_time..end_time})
    end

    if (avoid_schedule)
      course_schedule.course_sections.each do |course_section|
        details = course_section.course_meeting_details.first
        sched_start_time = details.try(:start_time)
        sched_end_time = details.try(:end_time)
        sched_days = details.days
        matches_query = matches_query.joins(:course_meeting_details)
                           .where.not(:course_meeting_details => {:start_time => sched_start_time..sched_end_time})
                           .where.not(:course_meeting_details => {:end_time => sched_start_time..sched_end_time})
                           .where.not(:course_meeting_details => days)
      end
    end

app/views/courses/index.html.erb
<% content_for :header do %>
  <%= render 'components/page_header', :title => "Course Planner", :subtitle => "Browse courses and plan your schedule" %>
<% end %>


<div class="notification is-info">
  <strong>Note:</strong> Pomona students <strong>are eligible for credit</strong> from CMC PE
  classes, despite the registrar listing them as 0.0 credits.
</div>

<div class="columns">
  <div class="column">
    <button class="button is-info is-outlined is-hidden-touch is-hidden-desktop-only" id="expand-course-planner">
      <span class="icon is-large margin-right-quarter">
        <i class="fa fa-arrows-h"></i>
      </span>
      <span id="expand-course-planner-text">
        Expand course planner
      </span>
    </button>
  </div>
</div>

<div class="columns">
  <div class="column is-3" id="course-search-form-container">
    <%= render 'courses/partials/course_search_form', academic_terms: @academic_terms, departments: @departments, course_meeting_details: @course_meeting_details %>
  </div>
  <div class="column is-4 is-hidden" id="course-list-container">
    <%= render 'courses/partials/course_list' %>
  </div>
  <div class="column">
    <div id="course-schedule-container">
      <%= render 'courses/partials/course_schedule', course_sections: @course_sections %>
    </div>
    <div class="buttons">
      <%= button_to "Save Schedule",
                    courses_save_path,
                    :class => "button is-link is-info",
                    :method => :post,
                    :remote => true %>
      <%= button_to "Clear Schedule",
                    courses_clear_path,
                    :class => "button is-light",
                    :method => :post,
                    :remote => true %>
      <%= button_to "Export Schedule",
                    courses_export_path,
                    :class => "button is-light",
                    :method => :get %>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<% content_for :header do %>
  <%= render 'components/page_header', :title => @course.name, :subtitle => "Reviews for #{@course.code}" %>
<% end %>

<% if @course.course_reviews.length > 0 %>
  <h2 class="title">Overall course rating: &nbsp;
    <span class="has-text-warning">
      <%= render 'components/numerical_review', rating: @course.overall_rating, tag_classes: 'is-large is-info', show_icon: true %>
    </span>
  </h2>
  <div class="columns">
    <div class="column">
      <h3 class="subtitle">
        Challenge rating: <%= render 'components/numerical_review', rating: @course.challenge_rating, tag_classes: 'is-medium' %>
      </h3>
    </div>
    <div class="column">
      <h3 class="subtitle">
        Inclusivity rating: <%= render 'components/numerical_review', rating: @course.inclusivity_rating, tag_classes: 'is-medium' %>
      </h3>
    </div>
    <div class="column">
      <h3 class="subtitle">
        Average work per week: <span class="tag is-medium"><%= @course.work_per_week %> hours</span>
      </h3>
    </div>
    <div class="column">
      <h3 class="subtitle">
        Average Cost: <span class="tag is-medium"><%= @course.total_cost %> dollars</span>
      </h3>
    </div>
  </div>
  <hr />
  <% @course.course_reviews.each do |review| %>
  <div class="columns">
    <div class="column">
      <div class="tags are-normal">
        <span class="tag is-medium">
          Course rating: &nbsp;
          <span class="has-text-warning">
            <%= render 'components/star_review', rating: review.overall_rating %>
          </span>
        </span>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column">
      <p class="subtitle"><%= review.comments %></p>
      <p><%= link_to instructor_path(review.instructor), :class => 'no-underline has-text-dark' do %>
          <%= review.instructor.name %>
          <%= render 'components/numerical_review',
                     rating: review.instructor.overall_rating %>
        <% end %></p>
    </div>
  </div>
  <div class="columns">
    <div class="column">
      <p><span class="tag has-background-white-bis"><%= review.work_per_week %> Hours work per week</span></p>
      <p><span class="tag has-background-white-bis">Cost: $<%= review.total_cost %></span></p>
      <p>
        <span class="tag has-background-white-bis">
          <span class="has-text-grey">
            <%= render 'components/star_review', rating: review.challenge_rating %>
          </span> &nbsp; Challenge rating
        </span>
      </p>
      <p>
        <% if review.inclusivity_rating %>
          <span class="tag has-background-white-bis">
            <span class="has-text-grey">
              <%= render 'components/star_review', rating: review.inclusivity_rating %>
            </span> &nbsp; Inclusivity rating
          </span>
        <% end %>
      </p>
    </div>
  </div>
  <div class="columns">
    <div class="column">
      <p><em>Review written <%= review.written_at %></em></p>
    </div>
  </div>
  <% if !current_user.nil? && review.user_id == current_user.id %>
    <div class="columns">
      <div class="column">
        <%= link_to "Delete", delete_course_review_path(review), :method => 'delete', class: "button is-danger is-outlined" %>
      </div>
    </div>
  <% end %>
  <hr />
  <% end %>
  <div class="columns">
    <div class="column">
      <p><%= link_to "Submit course review", new_course_review_path(@course.id), :class => 'button is-info' %></p>
    </div>
  </div>
<% else %>
  <div class="columns">
    <div class="column">
      <p class="subtitle">There are no reviews for this course at this time.</p>
      <p><%= link_to "Submit course review", new_course_review_path(@course.id), :class => 'button is-info' %></p>
    </div>
  </div>
<% end %>